In [1]:
import torch

In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x) # tensor([[1., 1.], [1., 1.]], requires_grad=True)
y = x + 2
print(y) # tensor([[3., 3.], [3., 3.]], grad_fn=<AddBackward0>)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
z = y * y * 3
out = z.mean()
print(z, out) # tensor([[27., 27.], [27., 27.]], 

out.backward()
print(x.grad) # tensor([[4.5000, 4.5000], [4.5000, 4.5000]])


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [12]:
# Specify device to be used
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
device = torch.device('mps' if torch.backends.mps.is_available() else
'cpu')
print(device)
# Create a tensor and move it to GPU
x = torch.ones([3, 3], device=device)
# Perform operations on the GPU
y = x + 2

cpu
mps


NameError: name 'model' is not defined